"use client";
import { Check, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ThemeSwitcher } from "@/components/theme/theme-switcher";
import { cn } from "@/lib/utils/cn";
const colors = [{ label: "Background", token: "--background", className: "bg-background" }, { label: "Surface", token: "--surface", className: "bg-surface" }, { label: "Card", token: "--surface-lowest", className: "bg-surface-lowest" }, { label: "Text", token: "--foreground", className: "bg-foreground" }, { label: "Border", token: "--border", className: "bg-border" }, { label: "Primary", token: "--primary", className: "bg-primary" }, { label: "Success", token: "--success", className: "bg-success" }, { label: "Warning", token: "--warning", className: "bg-warning" }, { label: "Danger", token: "--destructive", className: "bg-destructive" }];
function ThemePane({ dark }: { dark?: boolean }) { return <section className={cn("min-w-0 space-y-6 rounded-[var(--radius-lg)] border p-5", dark && "dark bg-background text-foreground")}><div className="flex items-center justify-between"><div><p className="type-label-caps text-muted-foreground">{dark ? "Dark mode" : "Light mode"}</p><h2 className="type-section-title">{dark ? "Low-glare control center" : "Warm operational canvas"}</h2></div><ThemeSwitcher /></div><div><p className="type-label-caps mb-3 text-muted-foreground">Color tokens</p><div className="grid grid-cols-3 gap-2 sm:grid-cols-5">{colors.map((color) => <div key={color.token} className="space-y-1"><div className={cn("h-8 rounded-[var(--radius)] border", color.className)} /><p className="type-body-sm truncate text-muted-foreground">{color.label}</p></div>)}</div></div><div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle>Component library</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2"><Button>Primary action</Button><Button className="bg-foreground text-background hover:bg-foreground/90">Secondary</Button><Button className="bg-transparent text-foreground hover:bg-muted">Ghost</Button></div><div className="flex flex-wrap gap-2"><Badge className="border-success/30 bg-success/10 text-success"><Check className="mr-1 h-3 w-3" />Confirmed</Badge><Badge className="border-warning/30 bg-warning/10 text-warning">Preparing</Badge><Badge className="border-destructive/30 bg-destructive/10 text-destructive">Cancelled</Badge></div><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input className="pl-9" placeholder="Search records" /></div></CardContent></Card><Card><CardHeader><CardTitle>Operational table</CardTitle></CardHeader><CardContent><div className="overflow-hidden rounded-[var(--radius)] border"><div className="grid grid-cols-3 border-b bg-surface-high px-3 py-2"><span className="type-table-header text-muted-foreground">Order</span><span className="type-table-header text-muted-foreground">Status</span><span className="type-table-header text-right text-muted-foreground">Total</span></div><div className="grid grid-cols-3 items-center px-3 py-3 text-sm hover:bg-muted"><span>#1048</span><span className="text-success">Ready</span><span className="text-right">$24.00</span></div></div></CardContent></Card></div></section>; }
export default function ThemePreviewPage() { return <main className="min-h-screen bg-background p-4 text-foreground sm:p-8"><div className="mx-auto max-w-[1440px] space-y-8"><header className="flex flex-wrap items-end justify-between gap-4 border-b pb-6"><div><p className="type-label-caps text-primary">Pro-Kitchen Admin</p><h1 className="type-display mt-2">Theme Preview</h1><p className="type-body-reg mt-2 text-muted-foreground">A shared visual foundation for precise restaurant operations.</p></div><ThemeSwitcher /></header><div className="grid gap-6 xl:grid-cols-2"><ThemePane /><ThemePane dark /></div><section className="rounded-[var(--radius-lg)] border bg-surface-low p-6"><p className="type-label-caps text-muted-foreground">Typography roles</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><p className="type-page-title">Page title</p><p className="type-section-title">Section title</p><p className="type-body-lg">Body large</p><p className="type-label-caps">Table header</p></div></section></div></main>; }
