"use client";
import Link from "next/link";
import { Mail, MoreVertical, Search, UserRound } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

type Administrator = { name: string; email: string; role: string; locations: string; lastActive: string; status: "Active" | "Pending" | "Inactive"; initials: string };
const admins: Administrator[] = [{ name: "Ali Khan", email: "ali.khan@pizzahouse.internal", role: "Restaurant Admin", locations: "All Locations (4)", lastActive: "2 mins ago", status: "Active", initials: "AK" }, { name: "Sara Malik", email: "sara.malik@pizzahouse.internal", role: "Kitchen Supervisor", locations: "Downtown Pizza House (#102)", lastActive: "3 hours ago", status: "Active", initials: "SM" }, { name: "Zainab Hassan", email: "zainab.hassan@pizzahouse.internal", role: "Finance & Billing", locations: "Westside Kitchen (#105)", lastActive: "Yesterday", status: "Pending", initials: "ZH" }];
const statusClass = { Active: "bg-success/10 text-success", Pending: "bg-warning/10 text-warning", Inactive: "bg-muted text-muted-foreground" };
export function AdministrationTable({ restaurantScoped = false }: { restaurantScoped?: boolean }) { return <Card className="overflow-hidden"><div className="flex flex-col gap-3 border-b bg-surface-low p-4 sm:flex-row sm:items-center sm:justify-between"><div className="relative w-full sm:w-80"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="h-9 pl-9" placeholder="Search administrators..." /></div><div className="flex gap-2"><select className="h-9 rounded-[var(--radius)] border bg-surface-lowest px-3 text-body-sm" aria-label="Filter administrators by role"><option>All Roles</option><option>Restaurant Admin</option><option>Supervisor</option></select><select className="h-9 rounded-[var(--radius)] border bg-surface-lowest px-3 text-body-sm" aria-label="Filter administrators by status"><option>All Status</option><option>Active</option><option>Pending</option></select></div></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="border-b bg-surface-high text-muted-foreground"><tr>{(restaurantScoped ? ["Administrator", "Role", "Status", "Last Login", "Added", "Actions"] : ["Administrator", "Role", "Locations", "Last Active", "Status", "Actions"]).map((heading) => <th key={heading} className="type-table-header px-6 py-3">{heading}</th>)}</tr></thead><tbody className="divide-y">{admins.map((admin) => <tr key={admin.email} className="hover:bg-muted"><td className="px-6 py-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-primary text-xs font-bold text-white">{admin.initials}</span><div><Link href={`/administrations/${admin.name.toLowerCase().replace(" ", "-")}`} className="text-body-sm font-semibold hover:text-primary">{admin.name}</Link><p className="flex items-center gap-1 text-xs text-muted-foreground"><Mail className="h-3 w-3" />{admin.email}</p></div></div></td><td className="px-6 py-4 text-body-sm">{admin.role}</td><td className="px-6 py-4 text-body-sm text-muted-foreground">{restaurantScoped ? <span className={`rounded-full px-2 py-1 text-xs font-semibold ${statusClass[admin.status]}`}>{admin.status}</span> : admin.locations}</td><td className="px-6 py-4 text-body-sm text-muted-foreground">{admin.lastActive}</td><td className="px-6 py-4 text-body-sm">{restaurantScoped ? "Jan 12, 2023" : <span className={`rounded-full px-2 py-1 text-xs font-semibold ${statusClass[admin.status]}`}>{admin.status}</span>}</td><td className="px-6 py-4 text-right"><button className="rounded p-1 text-muted-foreground hover:bg-muted hover:text-primary" aria-label={`Actions for ${admin.name}`}><MoreVertical className="h-4 w-4" /></button></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t bg-surface-low px-4 py-3 text-body-sm text-muted-foreground"><span>Showing 1 to 3 of 3 administrators</span><span>Page 1 of 1</span></div></Card>; }
export function AdminEmptyIcon() { return <div className="mb-6 flex h-20 w-20 items-center justify-center rounded-full border bg-surface text-muted-foreground"><UserRound className="h-9 w-9" /></div>; }
